# Use root/example as user/password credentials
version: '3.1'

services:
  # Spring Boo service configuration
  springboot-app:
    container_name: client-manager-service
    restart: always
    image: springboot-app
    build: .
    ports:
      - "9090:8080"
    environment:
      MYSQL_HOST: mysqldb-client-manager-service-container # localhost is == db.container_name: mysqldb-webbanking-app-container
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    depends_on:
    - db

# DataBase service configuration
  db:
    container_name: mysqldb-client-manager-service-container
    image: mysql:8.0.36
    restart: always
    command: --init-file /mysql_scripts/create_client_and_account_tables.sql # this command will create database
    volumes:
      - /Users/ivanhomziak/IdeaProjects/client-manager-service/db_data/db:/var/lib/mysql
      - ./create_client_and_account_tables.sql:/mysql_scripts/create_client_and_account_tables.sql # path to script which should create database
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: webbanking-db
      MYSQL_USER: student
      MYSQL_PASSWORD: student
#      MYSQL_HOST: localhost
      MYSQL_PORT: 3307:3306

    # (this is just an example, not intended to be a production configuration)
