# Use root/example as user/password credentials
version: '3.1'

services:
  # Spring Boo service configuration
  springboot-app:
    container_name: webbanking-app
    restart: always
    image: springboot-app
    build: .
    ports:
      - "9090:8080"
    environment:
      MYSQL_HOST: mysqldb-webbanking-app-container # localhost is == container_name: mysqldb-webbanking-app-container
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    depends_on:
    - db

# DataBase service configuration
  db:
    container_name: mysqldb-webbanking-app-container
    image: mysql:8.0.36
    restart: always
    volumes:
      - /Users/ivanhomziak/IdeaProjects/webbankingapp/db_data/db:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: webbanking-db
      MYSQL_ROOT_PASSWORD: root
#      MYSQL_PASSWORD: student
#      MYSQL_HOST: localhost
      MYSQL_PORT: 3307:3306

    # (this is just an example, not intended to be a production configuration)
