# Use root/example as user/password credentials
version: '3.1'

services:
  # Spring Boo service configuration
  springboot-app:
    container_name: client-manager-service-container
    restart: always
    image: springboot-app
    build: .
    ports:
      - "9090:8080"
    environment:
      MYSQL_HOST: mysqldb-client-manager-service-container # localhost is == db.container_name: mysqldb-client-manager-service-container
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    depends_on:
      - db

  # DataBase service configuration
  db:
    container_name: mysqldb-client-manager-service-container
    image: mysql:8.0.36
    restart: always
    command: --init-file /mysql_scripts/init_db.sql # this command will create database
    volumes:
      - ./db:/var/lib/mysql
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql # path to script which should create database
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: clients_db
      MYSQL_USER: student
      MYSQL_PASSWORD: student
      #      MYSQL_HOST: localhost
      MYSQL_PORT: 3307:3306

    # (this is just an example, not intended to be a production configuration)
