version: '3.1'

services:
  mysqldb:
    container_name: mysqldb-cms-c
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: clients_db
      MYSQL_USER: clientuser
      MYSQL_PASSWORD: clientpassword
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: admin1234
    ports:
      - "3307:3306"
    networks:
      - client-account-ms-net
    volumes:
      - ./mysql-camsdb:/docker-entrypoint-camsdbdb.d/ # path to script which should create database
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-padmin1234" ]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  client-account-ms-net:
  bankingapp-network:
    driver: bridge  # Connect to global network