spring:
  config:
    import: optional:configserver:http://localhost:8888
  devtools:
    restart:
      enabled: true
  docker:
    compose:
      enabled: true
  # Datasource connection
  sql:
    init:
      platform: mysql
      mode: always
  datasource:
    url: jdbc:mysql://localhost:3307/${DB_NAME:clients_db}?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&requireSSL=false&sslMode=DISABLED
    username: root
    password: admin1234

  # Hibernate
#  data:
#    rest:
#      base-path: /api
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        temp:
          use_jdbc_metadata_defaults: false
        format_sql: true
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

  flyway:
    baseline-on-migrate: true
    enabled: true
    user: root
    password: admin1234
    url: jdbc:mysql://localhost:3307/${DB_NAME:clients_db}?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&requireSSL=false&sslMode=DISABLED
#    baseline-description: "init"
    baseline-version: 1
#    database-type: mysql

  # Kafka Configuration
  kafka:
    template:
      default-topic: transfer-transactions-topic
    consumer:
      bootstrap-servers: localhost:29092
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: transaction-group
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"
    producer:
      bootstrap-servers: localhost:29092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    topic:
      transfer-transactions-topic: transfer-transactions-topic
      transaction-results-topic: transaction-results-topic

  # RabbitMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    # cloud.config.import-check.enabled: true

# Eureka Configuration
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}

# Logging Configuration
logging:
  level:
    org:
      springframework: ERROR
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    com:
      numericaideas: DEBUG
  file:
    name: client-account-ms.log

# Management Endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"

# Authentication Configuration
authorization:
  token:
    header:
      name: Authorization
      prefix: Bearer