spring:
  profiles:
    active: prod

  flyway:
    validate-on-migrate: true
    baseline-on-migrate: true

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
    enabled: true
  packages-to-scan: com.ihomziak
