name: Build & Deploy Spring App

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy Spring Boot bankingapp-client-account-ms
    runs-on: ubuntu-latest
    steps:
      - name: Checkout client-account-ms
        uses: actions/checkout@v4

      - name: Checkout bankingapp-common
        uses: actions/checkout@v4
        with:
          repository: IvanHomziak/bankingapp-common
          path: bankingapp-common

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: maven

      - name: Install bankingapp-common
        run: |
          cd bankingapp-common
          mvn clean install -DskipTests

      - name: Run Unit Tests for client-account-ms
        run: mvn -B test --file pom.xml

      - name: Build client-account-ms Application
        run: mvn clean package -DskipTests

      - name: Build Docker Image
        uses: actions/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_USERNAME }}/bankingapp-client-account-ms:$(date-'%Y-%m-%d%H-%M-%S')

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push image to Docker Hub
        uses: actions/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/bankingapp-client-account-ms:$(date-'%Y-%m-%d%H-%M-%S')
